### ISSUE TITLE
Add routine control

### ISSUE THREAD

**Issue by clucasalcantara** [brian-ai/core#7]
### Description

We need a routine control to create intents for Brian. The main concern is to provide a bridge (api, inside function, somehow) to understood comands and execute tasks. This task is on hold while the main functionalities list isn't ready yet.

If exists, add ideas, schemas or references below.

**Comment by Marlysson** [comment]
There are more description about this task?

**Comment by clucasalcantara** [comment]
Hi @Marlysson ! Not yet, only the main idea. 

Actually the "needing" it's to add the ability to answer to complex routines (scheduled or not), for example:

`intent: "wake up', actions: 'read weather info', 'open blinds', 'play maroon5'`

I'll think more about this and try to provide more info soon.
